#image: docker:latest
image: bug313/nrf_embuild

build:
  stage: build
  script:
    - echo "CI_BUILDS_DIR = $CI_BUILDS_DIR"
    - echo "CI_COMMIT_REF_NAME = $CI_COMMIT_REF_NAME"
    - echo "CI_COMMIT_SHORT_SHA = $CI_COMMIT_SHORT_SHA"
    - echo "CI_COMMIT_MESSAGE = $CI_COMMIT_MESSAGE"
    - echo "CI_JOB_NAME = $CI_JOB_NAME"
    - echo "CI_JOB_STAGE = $CI_JOB_STAGE"
    - echo "CI_PROJECT_DIR = $CI_PROJECT_DIR"
    - pwd
    - which git
    - emBuild
    - emBuild -verbose -config 'Release' $CI_PROJECT_DIR/dfu_template/ble_app_buttonless_dfu_pca10040_s132.emProject
    - cd $CI_PROJECT_DIR
    - git status
    - git log -1 --date=unix | grep "Date:" | rev | cut -d ' ' -f 1 | rev
    - git describe --always --abbrev=6 --dirty=-dirty
  artifacts:
#    name: "$CI_COMMIT_SHORT_SHA"
    paths: "binary"
    paths:
      - $CI_PROJECT_DIR/dfu_template/Output/Release/Exe/*.hex
    when: on_success
#  cache:
#    paths:
# Not beneficial as intermediates in cache are always older than source
#      - $CI_PROJECT_DIR/dfu_template/Output
#  services:
#    - bug313/nrf_embuild
#  tags:
#    - nrf_embuild
#  variables:
#    DOCKER_TLS_CERTDIR: ""
  only:
    - branches
    - tags
    - pushes
